package com.example.aaos_onelink.database

val AlarmConfig = hashMapOf(
    "1" to "Ignition Report",
    "2" to "Stall escalation",
    "3" to "Fortification Report",
    "4" to "Disarm report",
    "5" to "Door open.",
    "6" to "Door closed.",
    "7" to "System boot",
    "257" to "Trailer Alarm",
    "258" to "Location over long alarm",
    "259" to "Terminal Pull out alarm",
    "260" to "Terminal Insert Alarm",
    "261" to "Low voltage alarm",
    "262" to "Idling too long",
    "263" to "Speeding alarm",
    "264" to "Fatigue driving",
    "265" to "Water temperature Alarm",
    "266" to "High-speed gap glide",
    "267" to "Fuel consumption does not support alarm",
    "268" to "OBD does not support alerting",
    "269" to "Low water temperature High speed",
    "270" to "Bus does not sleep alarm",
    "271" to "Open the door illegally",
    "272" to "Illegal ignition",
    "273" to "Quick accelerationAlarm",
    "274" to "Emergency deceleration alarm",
    "275" to "Emergency Turn Alarm",
    "276" to "Collision Alarm",
    "277" to "Abnormal vibration Alarm",
    "278" to "Start spd up",
    "513" to "GPS Module Fault Alarm",
    "514" to "Flash fault Alarm",
    "515" to "Can module fault alarm",
    "516" to "3D Sensor Fault Alarm",
    "517" to "RTC Module Fault Alert",
    "518" to "Temperature sensor Fault Alarm",
    "519" to "Temperature sensor On-line Alarm",
    "769" to "The security glass is not off the alert.",
    "770" to "Lock car not successful reminder",
    "771" to "Timeout not fortified reminder",
    "772" to "Input and output status change"
)